In [2]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
ar=np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
a=np.array(l)

In [10]:
a

array([1, 2, 3, 4])

In [11]:
c=a

In [12]:
c

array([1, 2, 3, 4])

In [13]:
c[0]=100

In [14]:
c

array([100,   2,   3,   4])

In [15]:
a

array([100,   2,   3,   4])

In [17]:
np.fromfunction(lambda i , j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [18]:
np.fromfunction(lambda i , j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [19]:
iterable = (i*i for i in range(5))

In [20]:
np.fromiter(iterable , float)

array([ 0.,  1.,  4.,  9., 16.])

In [22]:
np.fromstring('234 234', sep= " ")

array([234., 234.])

In [23]:
l = [2,3,4,5,6]

In [24]:
ar = np.array(l)

In [25]:
ar

array([2, 3, 4, 5, 6])

In [26]:
ar.ndim

1

In [27]:
ar2= np.array([[1,2,3,4], [2,3,4,5]])

In [28]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [29]:
ar2.ndim

2

In [30]:
ar2.size

8

In [31]:
ar2.shape

(2, 4)

In [32]:
ar.dtype

dtype('int64')

In [36]:
ar22 = np.array([(1.2,45,45), (23,45,66)])

In [39]:
ar22

array([[ 1.2, 45. , 45. ],
       [23. , 45. , 66. ]])

In [40]:
list(range(5))

[0, 1, 2, 3, 4]

In [42]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [43]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [44]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [45]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.logspace(2,5,10 , base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [50]:
arr=np.random.randn(3,4) #here data meanis zero n st dev is 1

In [51]:
import pandas as pd

In [52]:
pd.DataFrame(arr)

0         1         2         3
0  1.909464 -1.330470  0.143491  0.508466
1  2.024320 -0.847773  0.923061 -1.008998
2 -1.446535 -1.969126  0.771473  0.079378

In [53]:
np.random.rand(3,4) #random function 

array([[0.02387876, 0.7079877 , 0.94240999, 0.30863767],
       [0.42817048, 0.19653089, 0.5873161 , 0.20882258],
       [0.8849164 , 0.10653419, 0.86712234, 0.7530261 ]])

In [56]:
np.random.randint(1,110 , (3,4))

array([[  9,  58,  85,  60],
       [ 98,  73,  38,  97],
       [106, 109,  40,  83]], dtype=int32)

In [58]:
pd.DataFrame(np.random.randint(1,110 , (300,400))).to_csv("test.csv")

In [60]:
arr=np.random.randint(1,100 , (5,5))

In [61]:
arr

array([[42, 64, 74, 51, 41],
       [14, 31, 94, 77, 90],
       [20, 34, 96, 47, 97],
       [97, 32, 10, 90, 73],
       [21, 98, 19, 11, 21]], dtype=int32)

In [65]:
arr[arr>50]

array([64, 74, 51, 94, 77, 90, 96, 97, 97, 90, 73, 98], dtype=int32)

In [66]:
arr[2:4 , [1,2]]

array([[34, 96],
       [32, 10]], dtype=int32)

In [67]:
arr[0][0]=432

In [68]:
arr

array([[432,  64,  74,  51,  41],
       [ 14,  31,  94,  77,  90],
       [ 20,  34,  96,  47,  97],
       [ 97,  32,  10,  90,  73],
       [ 21,  98,  19,  11,  21]], dtype=int32)

In [ ]:
# numpy broadcasting

In [69]:
arr = np.zeros((4,4))

In [73]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
row= np.array([1,2,3,4])

In [75]:
row

array([1, 2, 3, 4])

In [76]:
col= np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
Arr= np.array([2,3,1,5,8,4,3,9,8])

In [4]:
np.sort(Arr)

array([1, 2, 3, 3, 4, 5, 8, 8, 9])

In [5]:
np.searchsorted(Arr , 34)

np.int64(9)

In [6]:
Arr1= np.array([3,4,0,0,0,0,9,6,5,4])

In [7]:
np.count_nonzero(Arr1)

6

In [8]:
np.where([Arr>3])

(array([0, 0, 0, 0, 0]), array([3, 4, 5, 7, 8]))

In [9]:
np.extract(Arr>3 , Arr)

array([5, 8, 4, 9, 8])

In [10]:
a=np.copy(Arr)

In [11]:
a

array([2, 3, 1, 5, 8, 4, 3, 9, 8])

In [12]:
b=Arr.view()

In [13]:
b=Arr

In [14]:
b

array([2, 3, 1, 5, 8, 4, 3, 9, 8])

In [15]:
b[0]= 34

In [16]:
b

array([34,  3,  1,  5,  8,  4,  3,  9,  8])

In [17]:
Arr

array([34,  3,  1,  5,  8,  4,  3,  9,  8])

In [18]:
import numpy.matlib as nm

In [19]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [20]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
#numpy - linear algebra

In [25]:
crr1 = np.random.randint([[2,3], [4,5]])

In [28]:
crr2= np.random.randint([[5,3] , [2,5]])

In [29]:
np.dot(crr1 , crr2)

array([[1, 0],
       [2, 1]], dtype=int32)